### ISSUE TITLE
Missing colors in warning/error verbosity

### ISSUE THREAD

**Issue by agudmund** [pyblish/pyblish-base#139]
Within a blank scene and Pyblish loaded, the following command naturally produces an error on no instances found:

`pyblish.main.publish()`

 However, the end message in the verbosity log shows no internal coloring in the UI as is to be expected through `maya.cmds.warning` or `maya.cmds.error`

**Comment by mottosso** [comment]
Thanks, @agudmund this should be a quick fix. You're also welcome to submit a pull-request with the fix! :)

**Comment by mottosso** [comment]
What you're seeing in the script editor is actually the return value of `pyblish.main.publish()`. The error is printed just before it, and I'm not sure there is any way of making the error get printed _after_ the return value. Which is what we would need for a persistent color to appear for the user.

When running a publish via File|Publish however the error appears as expected, because the return value is bypassed due to it bring triggered by a menu-item.

Closing this, feel free to re-open if problems should arise.

> Note: This is in regards to the Maya Integration.

**Comment by agudmund** [comment]
Good point, keep the issue closed, it's enough to store the return value in a string and all the pretty colors appear as normal, i.e. `result = pyblish.main.publish()` rather than only `pyblish.main.publish()`
  If one wants to explicitly print out the return statement the string can of course be printed afterwards.

This works as well, and is PEP8 friendly:

`````` python
try:
    pyblish.main.publish()
except Warning as e:
    print e```

  Confirmed working fine through the menu as well.
``````
