### ISSUE TITLE
Multi line output using "pyblish.api.ValidationError" exception

### ISSUE THREAD

**Issue by ghost** [pyblish/pyblish-base#155]
Here is a question:

At the moment, I'm raising a `pyblish.ValidationError` that provides information to the user in several lines. That is because I want to add an URL so the user can get more information from the the `wiki` in our intranet:

``` python
raise pyblish.ValidationError("Namespaces found in the scene: %s\n"
    "Information on how to fix it: "
    "http://placeholder_wiki_url"
    % namespaces_in_scene)
```

I'm not sure if this is the best place to add the information or if you have something else in mind. Since we are aiming to use the GUI, I've noticed that as soon as I go to the next line, I would have to add at least 4 spaces of indentation to make it look as part of the same exception which is not ideal.

Again, adding this information to the exception might not be the best thing to do but I wanted to have a way to give the artist some information about how to get it fixed.

It would be great if you can share your thoughts on this.
Cheers,

**Comment by mottosso** [comment]
> I've noticed that as soon as I go to the next line, I would have to add at least 4 spaces of indentation to make it look as part of the same exception which is not ideal.

Interesting observation. You're right, at the moment, I'm adding 4 spaces in the Terminal to the output of an exception, which turns this:

``` python
raise Exception("Hello\nWorld!")
```

Into this:

``` json
    Hello
World!
```

# In the future

The idea is not to rely on the terminal for this information. 

I'm working on this now and will start showing some suggestions next week, but in a nutshell exceptions from plug-ins should provide users with _precise_ information about an error; whereas the doc-string of plug-ins provide the _background and general description_. 

We'll be able to "dig into" a plug-in and inspect it's properties and doc-string (which will become it's primary documentation). Until then, we could implement this into the terminal, but the problem lies in how it currently wraps the lines automatically. E.g.

``` python
This is a very very long line
```

Would become:

``` python
This is a
very very
long line
```

When the window is too small to fit the entire length. Having it wrap and add spaces only to error messages might be tricky to implement.

# Bottom line

> I'm not sure if this is the best place to add the information or if you have something else in mind. 

This is the best place for _specific_ info; that is, information including names of nodes or data related to a particular asset or scene. If the information is general enough, such as a link to the Wiki, then it's better to store this in the doc-string. We'll have a look at the type of formatting we can do with it - such as Markdown - once we get something to play with.

Alternatively, you could currently store documentation in a `doc` attribute of the plug-in, but I wouldn't rely on it just yet as, like I said, I'm still in the middle of things, but the idea would be to provide for Sphinx compatible doc-strings, and Pyblish compatible documentation (e.g. Markdown) at the same time.

``` python
class MyOrangeValidator(...):
    """To the developer, I do orange matrix equations"""

   doc = "To the artist, I *validate* the translate **values** of your ~oranges~"
```

# Bottom bottom line

The information in the exception along with docstring/docattribute will be front-and center of the GUI; available as tooltip, popup dialog, "diving into" a plug-in based on how a user chooses to view it. 

Once we've got this in a working state, the Terminal will most likely take a back seat to developers only; possibly only accessible via some less visible hotkey or nested menu item. Because of that, I wouldn't get too comfortable with the idea that artists will ever see it.

## Solution?

As a temporary measure, I could remove the initial spaces from happening, and instead leave a blank line at either side of the output?

Something like this.

**before**

``` python
MyOrangeValidator
    -----------------------------------------------
    INFO - Processing instance: "Steven11"
    -----------------------------------------------
    FAIL: I'm a really long message, and this
is a line break.

```

**after**

``` python

MyOrangeValidator
-----------------------------------------------
INFO

Processing instance: "Steven11"
-----------------------------------------------
FAIL

I'm a really long message, and this
is a line break.
```

**Comment by ghost** [comment]
> Alternatively, you could currently store documentation in a doc attribute of the plug-in, but I wouldn't rely on it just yet as, like I said, I'm still in the middle of things, but the idea would be to provide for Sphinx compatible doc-strings, and Pyblish compatible documentation (e.g. Markdown) at the same time.

I'll hold off for now but it does sound exciting!

> Once we've got this in a working state, the Terminal will most likely take a back seat to developers only; possibly only accessible via some less visible hotkey or nested menu item. Because of that, I wouldn't get too comfortable with the idea that artists will ever see it.

I couldn't agree more. In my experience it is not something that they would want to check anyway. But as a developer, this is the place where I tend to go when things go wrong. It will be useful to spot errors in the plugins themselves. As for hiding it from the regular user:  :+1: 

> As a temporary measure, I could remove the initial spaces from happening, and instead leave a blank line at either side of the output?

Sounds good to me

**Comment by mottosso** [comment]
> > As a temporary measure, I could remove the initial spaces from happening, and instead leave a blank line at either side of the output?
> 
> Sounds good to me

I'll do that!

**Comment by ghost** [comment]
:+1:

**Comment by mottosso** [comment]
How about something like this?

![untitled](https://cloud.githubusercontent.com/assets/2152766/6358713/8d61af54-bc65-11e4-8172-eed0ad446b88.gif)

The formatting is actually plain HTML, how would you feel about being able to provide your own formatting?

**Comment by ghost** [comment]
Does that mean I can add _links_, _colors_ and such? That would be sweet!

**Comment by mottosso** [comment]
I haven't experimented with it too much yet, but by the looks of it you might be able to do anything a webpage can; and that includes links.

You know, I just gave this a quick go, and yes, you can make clickable links this way. :)

If you add something like this to an error message, it'll produce a clickable link.

``` html
<a href=http://www.google.com>Click me</a>
```

In the next commit, that is.

**Comment by ghost** [comment]
I look forward to the next commit!

**Pyblish rocks!** :+1:

**Comment by ghost** [comment]
Is it up to the developer to color exceptions or will they be red by default?

**Comment by mottosso** [comment]
I made errors red by default. Along with a larger font-size for plug-in names, you don't need to do anything. But I'd expect to revisit this to make things a bit more 2015, and a little less 1984, now that we know HTML and CSS is neighbours.

**Comment by mottosso** [comment]
Here's a more practical demo.

![untitled](https://cloud.githubusercontent.com/assets/2152766/6359261/be614d4a-bc69-11e4-8134-3fd4e6e41997.gif)

Log messages are all white, and exceptions are red. And violets are blue.

**Comment by ghost** [comment]
:+1:
