### ISSUE TITLE
Plugin order

### ISSUE THREAD

**Issue by ghost** [pyblish/pyblish-base#159]
I know that at the moment it is not possible to define the order in which plugins are evaluated other than trick Pyblish by changing the plugin name so alphabetically it ends up where I want.

Is it worth to add an attribute that says something like:

'evaluate_after =[]'

Similar to the way we make it work on certain families.

At the moment I have some plugins that check the existence of certain nodes and I have another one that it is checking something within those nodes (such as existence of certain attribues).

I don't want to combine them because the group (could be complex hierarchy) exists within different types of asset but not the attribute.

It is true that I could combine them and create a different version depending on asset type but it feels like I will be duplicating code and it seems like I would not be taken advantage of the modular nature of the plugins.

Would that be feasible?

**Comment by mottosso** [comment]
I'd love for us to try and find a solution to this first.

Keep in mind that any new feature will have to be supported for the remaining lifetime of Pyblish and will be responsible for not just this solution but _all_ other solutions that could benefit from it.

Lets have a chat in Gitter?

**Comment by mottosso** [comment]
What @davidmartinezanim wanted to do, was to specifically run all validators and tally up their results into eventually being output to a file for post-inspection.

The issue was that the current event loop doesn't let you process any particular plug-in in a particular order; in this case the plug-in that does the logging will need to run last so as to capture all events from previous plug-ins.

We solved this by writing a simplified event loop that does just this.

Here's the discussion from Gitter.

> https://gitter.im/pyblish/pyblish/archives/2015/02/26

# Writing your own event-loop

For @davidmartinezanim, here's what pyblish.main.publish does in a nutshell.
1. Get all plug-ins
2. Run only the selectors
3. Run only the validators
4. If no validator failed, run only the extractors
5. If no validator failed, run only the conformers

In your case, to just run the validators and then log their results, you can skip most of these things and instead go with:
1. Get all plug-ins
2. Run selection
3. Run validation
4. Report

``` python
import pyblish.api

# 1. Get all plug-ins
context = pyblish.api.Context()
plugins = pyblish.api.discover()
errors = []

# 2. Run selection
for plugin in plugins:
    if issubclass(plugin, pyblish.api.Selector):
        for instance, error in plugin().process(context):
            pass # Don't care about errors.

# 3. Run validation
for plugin in plugins:
    if issubclass(plugin, pyblish.api.Validator):
        for instance, error in plugin().process(context):
            # The context will now have the instances from the Selection above
            if error is not None:
                errors.append(error)

# 4. Report
if errors:
    print "There were errors."
    for error in errors:
        print "- %s" % error
```

You could also use discover to filter type of plug-ins if that makes it easier to read.

``` python
for plugin in pyblish.api.discover("selectors"):
    ...

for plugin in pyblish.api.discover("validators"):
    ...
```
