### ISSUE TITLE
What is publish?

### ISSUE THREAD

**Issue by varjmes** [pyblish/pyblish-base#205]
Hi there,
I can’t find a text version of “what is pyblish” and your video doesn’t have captions, nor automated captions. Is there anywhere that lists what is happening in the video, for those that struggle with visual and audio impairments?

Thanks!

**Comment by mottosso** [comment]
Hi @Charlotteis,

Sorry about that, I'll have a look at adding captions to [the video](https://www.youtube.com/watch?v=j5uUTW702-U).

I'm not terribly familiar with providing captions or text versions to video, would it be possible to tell me a little bit about what you expect to find, and I'll see if I can get this set-up for you?

**Comment by mottosso** [comment]
Let me know if this helps!

### Video description

**00:00** The video starts with a cartoon character joyfully walking along, equally joyful music playing in the background.

**00:03** The title "What is Pyblish?" appears overlaid onto the video.

**00:07** The title slides off screen and opens up to the same character, standing in an unrendered default "t-pose" with his arms to his sides. This is the character as seen by one of the artists creating him.

**00:09** A menu appears. The mouse cursor hovers the item "Publish", which is provided by the software, and clicks it.

**00:12** A graphical user interface appears with the name "Pyblish" at the top. In it, a number of items are listed. The text "Share your content.." appears visibly in the top-right corner of the video.

In the GUI, to the left.

``` yaml
- Context
- RubberBoy
```

To the right.

``` yaml
- Validate: Rig members
- Validate: Bind pose
- Validate: Rig performance
- Validate: Channels
- Validate: Naming convention
- Validate: Default values
- Extract: Thumbnail
- Extract: Preview mesh
- Extract: Maya ASCII
- Integrate: Increment version
```

**00:14** The cursor hovers down to a Play button at the lower right corner of the GUI, and clicks it. Processing starts, and each item in the lists start showing signs of activity.

**00:15** Processing stops, two of the items in the GUI appear red, indicating that something related to them is wrong. The text "..but leave the mess" appears visibly in the lower-left corner of the video, a continuation of "Share your content..".

**00:17** The cursor hovers over one of the red items in the GUI, "Validate: Default values" and explores it.

**00:20** Inside of the red item, there is a warning message "Controls with non-defaults values detected" followed by "LeftArm_Upper_Arm.["rotateX"...]", indicating that this is where the problem is.

**00:30** The cursor selects the left arm of the character, and resets its translation values to 0.

**00:40** The Play button is hit once more, and this time, no warnings. The text "All clean!" appears visibly right underneath the character.

**00:45** The video closes with the character from the intro walking away. The text "Pyblish - test-driven content creation" appears visibly at the center of the screen.

The end.

**Comment by varjmes** [comment]
Thank you very much for your quick and awesome response! If you would like help captioning the video, then https://amara.org/en/ is a really good and free service. Having a captioned video will make your launch open to so many people (the hard of hearing, those with attention problems, those at work who don't have headphones and don't want to use sounds) so it's an awesome thing for you to do if you can.

Good luck with the launch, I will now read your transcript and see if I will use pyblish :)

**Comment by varjmes** [comment]
Oh, also the link to the example at the bottom of this repo's readme goes to a 404, wanted to let you know.

**Comment by mottosso** [comment]
Thanks @Charlotteis, I will have a look at this service! And thanks for the heads-up about the broken link, fixed now!

**Comment by mottosso** [comment]
I've added the above transcript to the description of the video on YouTube, hope that's ok!
