### ISSUE TITLE
Plug-in system

### ISSUE THREAD

**Issue by mottosso** [pyblish/pyblish-base#25]
To get the ball rolling on a potential plug-in architecture, I'll make some suggestions focusing on validations that might fit equally well for other aspects such as selection and extraction.
- See also [Pull-request](https://github.com/abstractfactory/publish/pull/24)
## Assumptions
1. Most if not all validations will be specific to a host; e.g. Maya validations probably won't apply to Houdini.
2. Our included validations (if any) will most likely reside in one place (e.g. the main Python package), but users will probably (and should) want to store their own validators separately; e.g. in their own repositories.
3. Validations may apply to multiple hosts
   - e.g. .. is this possible?
4. Validations may apply to multiple families
   - e.g. checking for unique names applies to both models and rigs
## Requirements

Based on the above assumptions, some of the requirements may be:
1. The location of potential validators must remain configurable
2. There must be support for multiple locations
   - `/publish/validators`
   - \+ `/root/studio_validators`
   - \+ `c:\more\validators`
3. Validators must identify which families they support
4. Validators must identify which hosts they support, e.g.
   
   ``` python
   # unique_names_validator.py example
   __families__ = ["model", "animation"]
   __hosts__ = ["maya"]
   ```
5. Validators must conform to a common interface, e.g.
   
   ``` python
   >>> for validator in validators:
   ...     try:
   ...         validator.run(context)
   ...     except:
   ...         if not autofix:
   ...             raise
   ...         try:
   ...             validator.fix(context)
   ...         except:
   ...             raise
   ```
6. Validators must be importable from any environment
   - e.g. A module written using maya.cmds won't be importable from the outside and thus not be introspectable for __families__ or __hosts__
## Implementation

These are some specifications for the [Pull-request](https://github.com/abstractfactory/publish/pull/24). Implementation is in [plugin.py](https://github.com/abstractfactory/publish/pull/24/files#diff-1d5ae802b52ec7051b41281f53140278R1) and tests are in [register_validators_test.py](https://github.com/abstractfactory/publish/pull/24/files#diff-0ec02011778625ae6eb3d815d4aa3519R1)

Logic can be summarised in three steps:
1. Register path with validators
2. Collect validators from registered path(s)
3. Use validators

Here is a summary of the behaviour:

(1.) Validations are separate modules
(2.) Each module is known as a plugin
(3.) The path for where plugins are stored are augmented by the user, e.g.

``` python
 >>> import publish.plugin
 >>> publish.plugin.register_plugin_path('c:\my\validators')
```
- See here [Registration](https://github.com/abstractfactory/publish/pull/24/files#diff-0ec02011778625ae6eb3d815d4aa3519R12)

(4.) Each plugin is wrapped in a Validator class which forwards the respective interface of each module. e.g.

``` python
 # unique_names_validator.py
 def process(context):
     pass

 def fix(context):
     pass

 # class interface
 validator = Validator(...)
 validator.process(context)
 validator.fix(context)
```

(5.) Each plugin is made importable by any process by performing localised imports, e.g.

``` python
def process(...):
    import host_dependent_module
```

**Comment by ljkart** [comment]
Nice thoughts.
validators should be like plugins and can be used as a check list where the studio has the complete authority to select and deselect (configurable) for particular department. Even we can create a validators library classified by department and users can easily plug to their system.

**Comment by BigRoy** [comment]
Should we make it a requirement that one could create their own subclassing hierarchy. Imagine a studio that does many mesh checks and they have a long list of Validators that operate only on polymeshes. They might want to do something like:

``` python
class MeshValidator(Validator):
    def process(self, context):
        meshes = maya.cmds.ls(context.nodes, type="mesh", long=True)
        return self.process_meshes(self, meshes)

    def process_meshes(self, meshes):
        raise NotImplementedError("Must be implemented in child class")


class MeshNormalsValidator(MeshValidator):
    def process_meshes(self, meshes):

        invalid_meshes = []
        for mesh in meshes:
            valid = check_normals(mesh)
            if not valid:
                invalid_meshes.append(mesh)

        self.invalid_meshes = invalid_meshes
        if invalid_meshes:
            return 0
        else:
            return 1
```

Or does the current setup disallow such workflow/implementation later on?
Note that we then might need to define a way for a class/plug-in to be designed as _Abstract_ so it doesn't get picked up by the plug-in system and/or interface and isn't allowed to process.

**Comment by mottosso** [comment]
> Or does the current setup disallow such workflow/implementation later on?

Sorry, I'm not following. Do you mean we should enforce the use of classes for validators, as opposed to flat modules? I'm currently working on an improved plug-in mechanism that uses classes; I was thinking to avoid it at first, but the benefits are beginning to stack up, one of which relates to checking for an associated base-class upon initial lookup.

**Comment by BigRoy** [comment]
I was mainly asking whether it would be possible to implement your own class hierarchies (to avoid code duplication everywhere) for when you do a lot of similar checks without breaking the plug-in system. I already tried something like that (the subclassing) in my fork (I'll do pull-request later!). It would be pretty convenient.

I guess you would need classes with that yes!

**Comment by mottosso** [comment]
Ah, code duplication. Yes, that would be another reason why classes is a win.

**Comment by BigRoy** [comment]
Just for inspiration/reference I wanted to link [YAPSY](http://yapsy.sourceforge.net/) which is a pretty minimalistic python Plug-in manager implementation.

**Comment by mottosso** [comment]
The design of our plugin-system is actually very similar to Yapsy, but it definitely makes sense to use something existing. Thanks @BigRoy

**Comment by ljkart** [comment]
We can  also consider Maya's plugin workflow, where we can ask any one to build their own plugin as a class and should contain a "compute()" method to do the process, as @BigRoy said we can provide them a abstract class is well.

**Comment by mottosso** [comment]
That's just how it works at the moment! :) Have a look at [validate_naming_convention.py](https://github.com/abstractfactory/publish/blob/83a4d729ff090e8e9d4922400637f0e78d558196/publish/validators/validate_naming_convention.py) to see what an implementation looks like, and [abstract.py](https://github.com/abstractfactory/publish/blob/83a4d729ff090e8e9d4922400637f0e78d558196/publish/abstract.py#L12) for the abstract class. From what I can tell, Yapsy also does this.

**Comment by BigRoy** [comment]
Currently I'm also in debate with myself about how to implement the Context (which represents the data stream/flow through the Filters).

I think each **Filter** can have _inputs_ and/or _outputs_ which result in an operation on the Context. Though since there will be a lot of different plug-ins to support the wide range of publishing situations I think it's best that the data stream can only hold predefined **Attribute** types, like _set, list, numerical, boolean, filepath, vector, etc._

An **Attribute** type ensures the data is stored in a consistent manner (like float is actually a float) and ensures we can't (for example) connect a list of strings to an integer input (thus avoid unexpected outcome).

If one has extra specific requirements, let's say wants to traverse his own data type of how one identifies an asset the first thing to do would be to implement the attribute type by inheriting from **Attribute**. (You can also define custom data in the Maya plug-in system, maybe we can look there as a reference as well.)

``` python
class MyValidator(Filter):
    def init(self):
        attr = FloatAttribute("maxDistance", input=True, output=True, required=True)
        self.add_attr(attr)

    def process(self):

        max = self.attr("maxDistance").get()
        max *= 10
        self.attr("maxDistance").set(max)   

        # Note that by overriding the __getattr__() and __setattr__() function for a 
        # Filter we can also allow for simply getting and setting the value like:
        #   max = self.maxDistance
        #   self.maxDistance = max * 10
        # This is also done in Pymel.
```

Note that this also has the benefit that the input/output of data that will be received from and passed on to the **Context** is not done by the user but is done automatically outside of `process()`. The user that defines a custom plug-in only handles the **Filter**'s own in- and outputs. This makes it a much better _black box_ design for the plug-ins.

Also using predefined datatypes (that can be extended with plug-ins) allows for data to flow through the graph in an understandable way.

**Comment by mottosso** [comment]
@BigRoy, do you think it would be possible to mock up a module with a working example of this? I'm still having trouble wrapping my head around where exactly the attributes come in. The validators at the moment have no attributes, nor inputs or outputs, and I haven't yet encountered anything missing from what it does.

For example, passing a model asset to a validator, like in [validate_naming_convention.py](https://github.com/abstractfactory/publish/blob/83a4d729ff090e8e9d4922400637f0e78d558196/publish/validators/validate_naming_convention.py). It has access to each individual node and does all of its processing from there. At the moment, it either succeeds (returns None) or fails (raises an exception). What else could get passed to it, and what else could get sent from it when done?

**Comment by BigRoy** [comment]
@mottosso This is because the validate_naming_convention.py only uses a single type of data from the current context, that is _the set of nodes_. What if I wanted to have selectors that also specify the _time range_ to use in the _validations_ or _extractions_. At the current stage this isn't possible because there's no way to also send through such data alongside the set of objects.

Even though in primary form and a very rough stage you could have a look at [my latest push in the nodegraph branch in my Publish forked repository](https://github.com/BigRoy/publish/commit/62df4feee3e16ca9110144c45891787f00cb0b5f). (Like before I'm still just making a mock-up and the code isn't actually doing something nice). Maybe it's already clear enough to provide more insight.

**Comment by mottosso** [comment]
> What if I wanted to have selectors that also specify the time range to use in the validations or extractions.

For this, you could use the `.config` member of each Instance.

``` python
>>> ...
>>> start_frame = instance.config.get('startFrame')
>>> extract(start=start_frame, end=end_frame)
```

The range could be configured within Maya itself, together with "family" and "publishable". Or it could come from elsewhere, in which case a Selector wouldn't necessarily need to be involved. For example, if the range came from Shotgun, it could be looked up against the current shot.

I'll definitely have a closer look at your implementation in a bit, but I think what I'm not quite getting is the higher-level usage of it.
1. User opens Maya
2. User creates asset
3. User collects related nodes in an objectSet
4. User tags objectSet with "publishable", "family" etc.
5. User runs publish

Where does the Attribute, Graph and the flow come in? A running example would make it crystal clear, but a 1-2-3 use-case would help a lot too!

**Comment by BigRoy** [comment]
Maybe I'm overthinking it yeah! Basically I figured that if the data was being 'set up' in the scene in Maya than having **Selectors** doesn't really make sense. Then we would just define a single way on how the context is retrieved and that's just the way it is.

On the other hand if everyone can implement their own way (using Selectors) on how the data for the **Context** is retrieved then all data should be retrieved by Selectors, among which would be _nodes to be published_ as well as _timerange_

I think we're both trying to tackle a similar problem but have a different vision, because I personally don't see where the `Instance` object comes into play. Probably because I'm replacing that with the Context/Attribute functionality.

The idea I have with the Selectors is that data that is being used for the publish can be somewhat dynamic. For example a **Selector** that takes the currently active time range for publishing. This wouldn't be possible with a static data field (not without expressions in Maya) represented in Maya. Another issue I see with the **config** stuff is that the example seems so Maya oriented whereas the **Selectors** feel more abstract.

Of course once I have something prototyped I'll try to explain it further; then we could also discuss more about whether that could work out.

---

I would opt for adding the following use case for testing purposes of _Publish_ to ensure we're software agnostic enough (it should be able to run standalone):
1. Get Context from file path: eg. find .mov files in a directory
2. Get Context from file path: eg. filter to only those that have been created after a certain date.
3. Validate that the file is at least bigger than 100 KB and smaller than 5 MB.
4. Extract a copy over to another Location.

**Comment by mottosso** [comment]
Ah, yeah I'm definitely liking the direction of where you're headed with pipes and filters, and for Selection to be more dynamic and adaptable; it's how its _used_ where I'm getting a little lost.

Are you thinking that **Selector** should be capable of doing something like _"select all nurbs curves"_ or _"select all nodes with attribute X"_ and so forth? This is one of the things that confuses me a little. It should ultimately be up to the artists to define what goes into a publish I think, along with how it publishes. Is that you're intent too? If so, how can they make use of that?

> because I personally don't see where the Instance object comes into play.

An **Instance** it what I'm referring to as the atomic unit that ultimately leaves a program; a **Context** then is a collection of instances. In a scene with multiple rigs, each output would be an instance. For single-asset scenes however there would only ever  be a single instance. **Instance** == **collection of nodes** + **their configuration** == **data** + **metadata**.

How are you envisioning this part?

**Comment by mottosso** [comment]
This is up and running and working fine, for future plugin alterations, let's make a new issue!
